CREATE TABLE IF NOT EXISTS games (
	id SERIAL PRIMARY KEY,
	game_title VARCHAR(64) NOT NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT(NOW())
);

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(64) NOT NULL UNIQUE,
	user_image VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS game_history (
	id SERIAL PRIMARY KEY,
	user_fk INT NOT NULL REFERENCES users(id),
	game_fk INT NOT NULL REFERENCES games(id),
	score INT NOT NULL DEFAULT(0),
	UNIQUE(user_fk, game_fk)
);
