// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package gamedb

import (
	"time"
)

type Game struct {
	ID        int32
	GameTitle string
	CreatedAt time.Time
}

type GameHistory struct {
	ID     int32
	UserFk int32
	GameFk int32
	Score  int32
}

type User struct {
	ID        int32
	Username  string
	UserImage string
}
