// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: queries.sql

package gamedb

import (
	"context"
)

const insertGame = `-- name: InsertGame :one
INSERT INTO games (game_title) VALUES ($1) RETURNING id
`

func (q *Queries) InsertGame(ctx context.Context, gametitle string) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertGame, gametitle)
	var id int32
	err := row.Scan(&id)
	return id, err
}
